set -g default-terminal "screen-256color"

unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix

set -g mouse on

unbind %
bind '\' split-window -h -c '#{pane_current_path}'
bind '¥' split-window -h -c '#{pane_current_path}'

unbind '"'
bind - split-window -v -c '#{pane_current_path}'

unbind r 
# tmux source-file ~/.tmux.conf \;
bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

# Copy vim movements
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# new window
bind c new-window -c '#{pane_current_path}'

# start from 1, not 0
set-option -g base-index 1
# re-number when closing windows
set-option -g renumber-windows on

# open a note for billion $ idea
bind -r e split-window -h "nvim ~/Documents/git/scratch/notes_$(date +'%Y%m%d%H').md"
bind -r v split-window -h -c "#{pane_current_path}" "zsh -c 'nvim; exec zsh'"
bind -r o split-window -h "nvim ~/Documents/git/scratch/todo_$(date +'%y%m%d').md"

# status bar new
# Configure the catppuccin plugin
set -g status-interval 120
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"

# set -g window-status-separator ""  # Removes the space between windows
# set -g @catppuccin_window_current_text_color "#{@thm_surface_1}"
# set -g @catppuccin_window_current_number_color "#{@thm_peach}"
# set -g @catppuccin_window_current_text "#[bg=#{@thm_mantle}] #{b:pane_current_path}"
#
# set -g @catppuccin_window_text " #W"
# set -g @catppuccin_window_default_text "#W" # show path for active panes, fallback to app name
# set -g @catppuccin_window_number_color "#{@thm_lavender}"

set -g status-left '#S '
set -g window-status-separator ' '
set -g window-status-current-format "#[fg=colour255,bg=colour62,bold] #I:#{b:pane_current_path} #[fg=white]"
set -g window-status-format "#I:#W #[fg=white]"
set -g status-style fg=white,bg=default

# Keep
set -g status-right-length 80 #character length
set -g status-right '#(curl -s wttr.in/kitaku?format=%%C+%%t+%%p+%%c)| %m-%d %H'

set -g status-left "#[bg=#{@thm_green},fg=#{@thm_crust}]#[reverse]█#[noreverse]#S "
set -g status-style fg=default,bg=default 

set -g status-bg default
set -g status-style bg=default

# Clean title bar - only show 'tmux' (placed at end to avoid plugin override)
set -g set-titles on
set -g set-titles-string "tmux"